### PR TITLE
mcfgthread-git: Update to master

### PR DESCRIPTION
**Pull request by lhmouse**
Signed-off-by: LIU Hao <lh_mouse@126.com>

### CODE REVIEW

**Comment by Biswa96** [comment]
Also need `"${MINGW_PACKAGE_PREFIX}-autotools"`

**Comment by lhmouse** [comment]
Thanks for the information. Updated.

**Comment by lhmouse** [comment]
@lazka Would you please merge this? Thanks in advance.

**Comment by lhmouse** [comment]
Thank you!

**Pull request merged**
